# Generated by Django 5.1 on 2024-08-27 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('designation', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\d{10,13}$')])),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('website', models.URLField(verbose_name='Website Link')),
                ('email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('domain', models.CharField(max_length=100)),
                ('experience', models.CharField(choices=[('Fresher', 'Fresher'), ('Experienced', 'Experienced')], max_length=50)),
                ('positions', models.IntegerField(verbose_name='No. of Vacancies:')),
                ('location', models.CharField(max_length=300)),
                ('job_description', models.FileField(blank=True, null=True, upload_to='job_descriptions/', verbose_name='Job Description')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='Profile Picture')),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
