# Generated by Django 5.1 on 2024-08-28 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitech', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterequirement',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date Added'),
            preserve_default=False,
        ),
    ]
