# Generated by Django 5.1 on 2024-08-29 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitech', '0002_candidaterequirement_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidaterequirement',
            name='salary',
            field=models.CharField(default=0, max_length=50, verbose_name='Package'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidaterequirement',
            name='experience',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('1-2 Years', '1-2 Years'), ('2-3 Years', '2-3 Years'), ('3-4 Years', '3-4 Years'), ('5+ Years', '5+ Years')], max_length=50),
        ),
    ]
