# Generated by Django 4.2.16 on 2024-09-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitech', '0005_internshipstudents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterequirement',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
