# Generated by Django 4.2.16 on 2024-09-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitech', '0006_alter_candidaterequirement_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterequirement',
            name='full_name',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
    ]
