# Generated by Django 4.2.16 on 2024-09-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uitech', '0007_alter_candidaterequirement_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidaterequirement',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
